### ISSUE TITLE
Fractions vs channels

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#11]
I think we should clarify fractions (along the gradient) and channels (the final columns in the data).

**Comment by lmsimp** [comment]
I had a chat with Claire today about this. She thinks there is often confusion with biologists between RP fractions from the MS and gradient fractions collected in the fractionation stage and mentioned that after data is imported into R she also refers to the quantitative columns as channels (not as fractions). I think I have clarified this now. See 5a8c0aa98388bf642f6965c20eecf0412de46053
