### ISSUE TITLE
Interactive visalisation section

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#14]
What about preparing short films instead of screenshots for the _Interactive visualisation_ section?

**Comment by lgatto** [comment]
Or, maybe, a include a `shiny` app! Wow!

**Comment by lmsimp** [comment]
GIF with link to actual app?

**Comment by lmsimp** [comment]
![prolocvis_pca](https://cloud.githubusercontent.com/assets/1698853/18410227/33291d96-7754-11e6-8a04-0c83c932bf07.gif)
@lgatto grainy and speedy! I will try re-rendering

**Comment by lmsimp** [comment]
What about this? Do f1000 accept GIFs?

**Comment by lgatto** [comment]
I suggest we put in the html version. Need to read up if it's possible in pdf via LaTeX (I think it is).
