### ISSUE TITLE
Confusion between naming MSnSets

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#15]
Reminder to check use of `hl` and `hyperLOPIT` as examples. One is combined from loading to independent replicates, the other is loaded from a csv already been combined

**Comment by lmsimp** [comment]
@lgatto I have updated as we discussed. What about when we run `phenoDisco` and `svmClassification`? These objects are called `pdRes` and `svmRes` respectively. Do you want me to keep them as `hl` and just add to the `fData` slot as we did for the protocol or would you like these left as they are?

**Comment by lgatto** [comment]
I would suggest to keep `hl` throughout the document, and document/show (on PCA plots for example, or using `getMarkers(, fcol = "...")`) the outputs. There is actually no reason not to overwrite the object.
