### ISSUE TITLE
Add evaluation of separation

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#17]

**Comment by lmsimp** [comment]
I think you have decided to leave this out of the workflow for now as only relevant when comparing multiple datasets?

**Comment by lgatto** [comment]
Let's just add a sentence and reference the QSep manuscript.

**Comment by lmsimp** [comment]
What's the latest with this? Do you plan to still include?

**Comment by lgatto** [comment]
Just leave it there for now and will see during final reading
