### ISSUE TITLE
Use Bioconductor release 3.3

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#2]
The manuscript/vignette should be build using the recent (yesterday) release (stable) version 3.3, as that is what readers/users will be assumed to use. To make use of that version, you will need R 3.3.

**Comment by lmsimp** [comment]
Have you decided what you are going to do about this? Have 2 versions of R? Two libraries? One with stable packages and one devel?

**Comment by lgatto** [comment]
I plan to have at least two R installations, `R-patched` and `R-devel` and probably 2 or 3 libraries. To install R, I use these [scripts](https://gist.github.com/lgatto/84f159d63c7a68211f026c03e9f7898d).

In `R-patched`'s `Renvironment` file, I defined `R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-pc-linux-gnu-library/3.3rel'}` and made sure that `BiocInstaller::useDevel(FALSE)`.

`R-devel` will use the default personal library `'~/R/x86_64-pc-linux-gnu-library/3.3`. 

It would be good to have an `R-patched` and `useDevel(TRUE)`. For this, I will probably create a small R function in my `.Rprofile` to switch to/from the personal library and `useDevel(TRUE/FALSE)`.

**Comment by lgatto** [comment]
I have 2 versions installed: `R-devel` and `R-3.3 (patched)` and 2 libraries `3.3rel` (for Bioc release using `R-3.3` and `3.4` for Bioc devel using `R-devel` and `R-3.3`. `R-3.3` has `R_LIBS_USER` pointing to `3.3rel` (updated, as default would be `3.3`) and `R-devel` has `R_LIBS_USER` pointing to `3.4`. To use `R-3.3` with Bioc devel, run it with `R_LIBS_USER='~/R/x86_64-pc-linux-gnu-library/3.4' R-3.3`.

**Comment by lmsimp** [comment]
Thanks

**Comment by lgatto** [comment]
We will have to build the workflow against the stable version of Bioc. `pRolocdata`, for instance, will require the devel version, due to the latest `bpw` additions. Let's see how much there would be to backport...

**Comment by lgatto** [comment]
Now using release 3.4.
