### ISSUE TITLE
how to store data

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#20]
options:
- add results from the `phenoDisco` run, TL, SVM classification to a new object called `hl` and add to `pRolocdata`? Then load using the function `data`? The bad side of this is we have then multiple datasets in `pRolocdata` containing the same quantitation information
- add results as columns to `hyperLOPIT2015`. I would rather not do this as the `fData` gets bigger and then there are many similar columns
- add `.rda` or other file type to `extdata` in `pRolocdata` and load using `dir` function with appropriate read function? I think this is the best option?

@lgatto  or other suggestions?

**Comment by lgatto** [comment]
Yes, I prefer to add `rds` files in `pRolocdata/inst/extdata` and then read then with `x <- readRDS(...)`. But we don't need to store full `MSnSet`; just the relevant `vector`/`factor` or optimisation results is enough. These objects should be names `bpw-...rds` and then documented in the `README` file under the `Bioconductor pRoloc workflow` section.

**Comment by lmsimp** [comment]
To add to `pRolocdata` and update workflow by loading `rds` of the following
- [x] tl opt results
- [x] pd new clusters results
- [x] svm opt results
- [x] add gocc dataset
