### ISSUE TITLE
clustering

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#23]
Mention somewhere that we can do clustering but a totally unsupervised approach not an appropriate/adaquete data analyses for spatial proteomics. It is still useful.... for clustering of markers, ref `mrkHClust`

**Comment by lmsimp** [comment]
Added a small section but may need work

**Comment by lgatto** [comment]
Also need to export from `pRoloc`.
