### ISSUE TITLE
Questions/checks in the manuscript

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#27]
> On figure 7, we plot the profile of the mitochondrial and peroxisome markers to highlight the differences in profiles between these two sets of markers along the 6th and 7th channels, as represented above along the 7th PC on the PCA plot.

This is confusing as the channels and indices on the y axis of `plotDist` don't match. Also, I have the feeling that it's not really along the 12th and 13th (TMT channels 6 and 7), but 13th and 14th columns that the data differs most.

**Comment by lgatto** [comment]
Similar question for table 1.

**Comment by lmsimp** [comment]
fixed in 1a3ed982b92a4c085ad77ad2b585384aacfa05a8
