### ISSUE TITLE
Suppl file with code to run on cluster

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#28]

**Comment by lmsimp** [comment]
Is this in reference to the TL code?

**Comment by lgatto** [comment]
> Is this in reference to the TL code?

Yes - I think we refer to such a file in the text, don't we?

**Comment by lmsimp** [comment]
I have added the submission file and R code to [this folder called code](https://github.com/lmsimp/bioc-pRoloc-hyperLOPIT-workflow/tree/master/code).

We may wish to modify bit of both of these files to make more generic?
