### ISSUE TITLE
Mention protein grouping issues with combining?

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#30]
Should we mention this? This will always be a problem. We should mention advantages of combining in Proteome Discovered vs `MSnbase`?

**Comment by lgatto** [comment]
No, that's an issue of proteomics data processing, only indirectly touching the actual subject of the workflow. There would be so much more to discuss if we went down that route - that's material for another workflow :-)
