### ISSUE TITLE
Inconsistent use of an and a before MSnSet

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#31]

**Comment by lgatto** [comment]
I am the one who uses _an_ `MSnSet` - is this wrong?

**Comment by lmsimp** [comment]
I actually don't know! An sounds right? But grammatically it should be 'a'? Need to check!

**Comment by lgatto** [comment]
My French grammar would rather point toward _an_. Let's ask Mike tomorrow :-)

**Comment by lmsimp** [comment]
I think it is 'an' see http://www.grammar.com/a-vs-an-when-to-use/

**Comment by lmsimp** [comment]
You beat me to it!
