### ISSUE TITLE
TL

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#32]
Highlight where TL is useful at the beginning of section. We say towards the end particularly useful for datasets with low cluster resolution, would be good to emphasise this where TL is first introduced.

**Comment by lmsimp** [comment]
Have added a sentence in this commit 8adb243a0c54078e668e42d4c7d9d18a65428220 you can probably make it more eloquent!

**Comment by lgatto** [comment]
What sentence?

**Comment by lmsimp** [comment]
Whoops didn't push properly as internet failed. Sorry this commit e1837d66605fa0e7a237ba9899a8b83656898ee4
