### ISSUE TITLE
Topics to add

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#34]
- `FeaturesOfInterest`
- `plot3D`
- `QSep`
- ~GO annotations~
- Future directions (multi/trans- localisation, automation, ...)

**Comment by lmsimp** [comment]
Agreed to not add GO annotations for now. This will form part of another manuscript.

Have added `plot3D` to the list.

**Comment by lmsimp** [comment]
Had a quick look at [similar workflows](https://f1000research.com/articles/4-1070/v1) in f1000 and no section on future directions.

@lgatto can you look at new 'FeaturesOfInterest' section?

Do you think we need to add a figure for `plot3D`?

**Comment by lmsimp** [comment]
- [x] Add `plot3D` figure, modify code and text where appropriate (to be added where we display PCs 1 and 7 etc)

**Comment by lgatto** [comment]
@lmsimp - could you push the `plot3D` figure? I will add it in the article later.

**Comment by lmsimp** [comment]
@lgatto plots have been added see [pcas-combined-plot.pdf](https://github.com/lmsimp/bioc-pRoloc-hyperLOPIT-workflow/blob/master/Figures/pcas-combined-plot.pdf) and for individual 3D plot [plot3D.pdf](https://github.com/lmsimp/bioc-pRoloc-hyperLOPIT-workflow/blob/master/Figures/plot3d.pdf)

**Comment by lgatto** [comment]
Thanks! Only needing the screenshot for the 3D plot - the others will still be generated dynamically.
