### ISSUE TITLE
Fig 6

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#39]
@lgatto can you regenerate this figure so that the x-axis labels on the LHS plot is `las = 2` and same font size are plot of the RHS?

**Comment by lgatto** [comment]
Unfortunately not; this would require changed in `plotDist`, which we could do, but only in devel and hence not for this submission.

**Comment by lgatto** [comment]
Actually, it is possible, but they overlap with `xlab`. Needs margin tweaking, then should be fine.

**Comment by lgatto** [comment]
Done, but requires latest `pRoloc` (1.15.5/1.14.5).
