### ISSUE TITLE
Would like to use addGoAnnotations

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#4]
@lgatto Do you think it would be nice to use this in this workflow? It would fit in nicely in the markers section where I add markers from (1) `pRolocmarkers` and then (2) show the curated markers. Of course, the restriction is however that this is not in the stable version of `pRoloc` and it's a lot of code to backport... and not to mention not good practice.

**Comment by lgatto** [comment]
I think that's an excellent idea. `addGoAnnotations` is available in the release branch - any additional changes we need to backport?

**Comment by lmsimp** [comment]
Ah, I thought we had missed the Bioc release and it was in devel. Great, so it's in stable! No backporting needed! :-) Closing this issue.
