### ISSUE TITLE
Daniel's review comments to address

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#40]
*Breckels et al. have written a very nice piece on analysing appropriate proteomics data for subcellular localisation. I particularly like the "workshop characteristics" of the text. Which allows a novice, but interested reader to work through the analysis stepwise and reproduce the results described therein. The authors took great care in keeping this ideal up during their text and this is also where I have put my greatest reservation to the manuscript in its present form - since a reader cannot work through the code presented in the manuscript, since there at at least two situations where a readily available HPC and quite some time is required. This kind of leaves a dent in my impression - however, given this can be resolved as well as some typos - the workflow report is superb.*

> **Major comments:**
- [x] *Next to reducing the dimensions of data for visualisation, PCA also offers a way to understand how the variability is distributed across the multidimensional data by providing linear combinations of the variables which then constitute the actual PCs. On that note it would be nice to mention this in Visualising markers section on page 16, where PC7 explains not much variability but due to the correct weighing of the variables we do get a separation between mitochondrial and peroxisome. This then can be further motivated with Figure 9 - where we probably can see that the weights for the fractions where the two localisations differ are larger than otherwise.*

We have added a paragraph to the 'Visualising markers' section of the manuscript reiterating the purpose of PCA and motivating the choice of looking at PC's 1 and 7. Figure 9 now follows on from this (now Figure 8), along with the corresponding code and an explanation of the `plotDist` function.

- [x] *I was unable to reproduce Figure 13 comparing the two MSnSets. While I was able to look at each set separately using pRolocVis(hllst@x[[I]]), where i is 1 or 2, I only got an error using the code from the manuscript. When using ‘remap=FALSE’ it actually works, but since this makes barely sense it is of no use - but just as a hint at debugging it.*

```r pRolocVis(hllst, app=“compare”)
Subsetting MSnSetList to their common feature names
5032 features in common
Remapping data to the same PC space
Error in (function (od, vd)  : 
  object and replacement value dimnames differ
Error in pRolocVis_compare(object, ...) : object 'idDT' not found
```

We can not reproduce this error. Have you updated to the latest version of R and the latest version of `pRolocGUI`? If you still get this error message could you please post this as an [issue](https://github.com/ComputationalProteomicsUnit/pRolocGUI/issues) on the `pRolocGUI` Github page along with your `SessionInfo()` and we will certainly attempt to solve this.

- [x] *You really need to make the results from the phenoDisco classification available too. It is super disappointing that one cannot continue reproducing the code from page 23 on, because it takes 24 hours to compute it using 40 cores…*

The results are already available as a `RDS` file and stored in `pRolocdata` for users. This is what is called in the manuscript under the hood:

```r
f0 <- dir(extdatadir, full.names = TRUE, pattern = "bpw-pdres.rds")
pdres <- readRDS(f0)
hl <- addMarkers(hl, pdres, mcol = "pd", verbose = FALSE)
```
We have made this code available in the manuscript in an appendix so users can continue to produce the exact plots as they see in this workflow. 

- [x] *The above comment is of course also true for the KNN TL Optimisation on page 33 - this needs to be downloadable, since not everyone has access to Cambridge’s HPC and probably even less have 76 hours to spare.*

The same as for the `phenoDisco` analysis and `svm`, the TL results are stored as a `RDS` in `pRolocdata` and are loaded in the background. We have added the code required to the appendix so that users can load the results directly.
 

- [x] *Your comment on the increase suitability of classification instead of clustering (when additional information on classes is available) at the bottom of page 35 could be more pronounced - for educational reasons.*

To address the above comment on suitability we have added a few additional points on the challenges of using clustering for this type of data.

We generally find supervised learning more suited to the task of protein localisation prediction in which we use high-quality curated marker proteins to build a classifier, instead of using an entirely
unsupervised approach to look for clusters and then look for enrichment of organelles and complexes. In the latter we do not make good use of valuable prior knowledge, and in our experience unsupervised clustering can be extremely difficult due to (i) the loose definition of what constitutes a cluster (for example whether it is defined by the quantitative data or the localisation information), (ii) the influence of the algorithm assumption on the cluster identification (for example parametric or non-parametric) and (iii) poor estimates of the number of clusters that may appear in the data.

**Minor comments:**
- [x] *I was not able to naïvely reproduce the workflow from the R commands in the article due to an error installing pRolocdata on a Windows machine. On OS X it was smooth.*

We didn't experience any problems with installing `pRolocdata` on Windows. If you re-try the installation and please let us know if you still have any issues by opening an [issue on Github](https://github.com/lgatto/pRolocdata/issues) or posting on the [Bioconductor Support site](https://support.bioconductor.org). 
 
- [x] *On page 10 line 2 there is a ‘to’ missing.*

In this version we currently can't find the missing 'to'. 

- [x] *I never came across the verb imputate in the context of missing values, I guess the proper term is impute.*

This has been changed to read "We can impute missing data..."

- [x] *On page 11 the image2 function is called after the filterNA function a couple of lines above. This however would result in an only black heat map (since there are no more missing). The image2 function should be called before the filterNA function. Since the reader does not see the chunk options, it could be puzzling.*

This was an editing mistake and has now been rectified
 
- [x] *For completeness sake there should also be an install.packages(c(“hexbin”, “rgl”)) somewhere to generate the second PCA-plot and the 3D plot. Moreover, Mac users will need to install xquartz to use rgl properly.*

A footnote has been added here to tell users that the package `rgl` may need to be installed with `install.packages("rgl")` and mac users may need to install xquartz if it's not already installed.

- [x] *On page 14 the plotting code chunk is off track - in the middle of the marker sets output.*

This has now been rectified.
 

- [x] *On page 18: …wanted to highlight a proteins with the… -> lose the a and later in the sentence there is a ‘create a’ too many.*
 
These typos have been rectified.

- [x] *Direct comparisons of individual channels in replicated experiments do not provide…*
 
This typo has been rectified.

- [x] *You may want to consider adding a layout(1) or similar, after changing the mfrow argument of the parameters to accommodate 2 panels, such that the uncanny reader does not get confused.*

We would prefer to keep the code as it is and not introduce more noise with calls to other functions such as `layout`. The workflow is not aimed at teaching `R`. Users should have some basic knowledge of `R` before tackling this tutorial. 

- [x] *I would prefer links to referred sections of the text, but that may be personal taste…*
This is a comment for f1000. We can not control the linking of sections in the final version.

- [x] *Page 23: One should note that the decreasing the GS, and increasing the … at least one the too many, probably two.*
 
We have reworded this sentence as requested.

- [x] *On page 25: We find the general tendancy to be that it is not the choice … tendency?*
 
This typo has been rectified.

- [x] *On page 28 you refer to ‘…the code chunk below…’ for Figure 17, however, the following code chunk is generating Figure 16 (which is above and btw not referenced in the text). Maybe force your figures a little to float where you want them/refer to them.*

We have now referenced Figure 16 in the text and made sure that the code chunks and figures follow inline where they are referenced in the text.
 
- [x] *On page 28: …by extracting the median or 3rd quantile score per organelle… do you mean quartile? Otherwise I do not follow.*

Thank you, yes this is a typo and has now been changed to 'quartile'.
 
- [x] *On page 32: …package to query the relevent database … relevant?*

This typo has been rectified 

- [x] *On page 32 - there is something wrong with this sentence: To remove the 4 classes and create a new column of markers in the feature data called tlmarkers to use for the analysis:*
 
This sentence is not needed here and so it has now been removed as it essentially reiterates what is said in the above paragraph.

- [x] *On page 34: From examining the parameter seach plots as described in section Optimisation… search!*

This typo has been rectified. 

- [x] *On page 36: …and later reload the object using save. -> that would be ‘load’ then!*
 
This typo has been rectified.

- [x] *On page 38 -  I fully agree with the following sentence, but right after the updating comment it kind of seems ‘misplaced’? Maybe add a title like ‘Getting help’?*

We have changed the title of this section to 'Session information and getting help' to clarify this section of the tutorial.

**Comment by lgatto** [comment]
Here's a suggestion for the classification vs clustering remark:

In the latter we do not make good use of valuable prior knowledge, and in our experience unsupervised clustering can be extremely difficult due to the loose definition of what constitutes a cluster (for example whether it is defined by the quantitative data or the localisation information), the influence of the algorithm assumption on the cluster identification (for example parametric or non-parametric) and the to poor estimates of the number of clusters that may appear in the data.

What do you think?

**Comment by lmsimp** [comment]
@lgatto Yes I think that's fine. Just added numbering for clarity

We generally find supervised learning more suited to the task of protein localisation prediction in which we use high-quality curated marker proteins to build a classifier, instead of using an entirely
unsupervised approach to look for clusters and then look for enrichment of organelles and complexes. In the latter we do not make good use of valuable prior knowledge, and in our experience unsupervised clustering can be extremely difficult due to (i) the loose definition of what constitutes a cluster (for example whether it is defined by the quantitative data or the localisation information), (ii) the influence of the algorithm assumption on the cluster identification (for example parametric or non-parametric) and (iii) poor estimates of the number of clusters that may appear in the data.
