### ISSUE TITLE
Leonard's review comments to address

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#41]
This manuscript describes a Bioconductor workflow for analyzing subcellular proteomics data. It is very detailed and comprehensive and will be useful for others in the field. 

A few comments:

- [x] Some clearer statement early on would help to clarify for readers what types of data this works with. I know that the authors indicate that the example they use is 10-plex TMT and that it can be used with label-free or other labels, but that is not what I am referring to. Rather, structure of the experiment. That is, that one needs systematic quantitative data on all the different relevant fractions from a cell, as opposed to someone who perhaps did a differential centrifugation experiment to isolate a couple fractions and then wants to apply this (my understanding is that this latter example would not be usable).
 
- [x] How do the authors recommend collapsing replicates? This could be covered in the section dedicated to the Compare function. Two replicates will (almost) never agree 100% so how are discrepancies handled?

**Comment by lgatto** [comment]
> Some clearer statement early on would help to clarify for readers what types of data this works with. I know that the authors indicate that the example they use is 10-plex TMT and that it can be used with label-free or other labels, but that is not what I am referring to. Rather, structure of the experiment. That is, that one needs systematic quantitative data on all the different relevant fractions from a cell, as opposed to someone who perhaps did a differential centrifugation experiment to isolate a couple fractions and then wants to apply this (my understanding is that this latter example would not be usable).


From a purely technical point of view, we need a data matrix with features (typically proteins or protein groups) along the rows and sub-cellular fractions along the columns. Given the requirement for
complete (or near-complete) quantitative vectors along all fractions to assure best results, a data set that would only contain one quantitation value per fraction would not work. However, separation
using differential centrifugation, or any separation that generates organelle-specific separation profiles is a good fit for pRoloc. For instance, the type of data generated by methods such as described in
Itzhak *et al.* (2016) [1] are well fitted for our software:

```r
> library(pRoloc)
> library(pRolocdata)
> data(itzhak2016stcSILAC)
> ## 6 combined replicates of 5 fractions each
> dim(itzhak2016stcSILAC)
[1] 5265   30
> plot2D(itzhak2016stcSILAC)
```
![rplot001](https://user-images.githubusercontent.com/384198/38307454-bcbcca5c-380b-11e8-8a41-d8f998ca2564.png)

If there were only very few fractions (say cytosol, nucleus and plasma membrane), the infrastructure could still be used, although for less benefits. 

[1] Itzhak DN, Tyanova S, Cox J, Borner GH. Global, quantitative and dynamic mapping of protein subcellular localization. Elife. 2016 Jun 9;5. pii: e16950.  doi: 10.7554/eLife.16950. PubMed PMID: 27278775; PubMed Central PMCID: PMC4959882.

**Comment by lgatto** [comment]
> How do the authors recommend collapsing replicates? This could be covered in the section dedicated to the Compare function. Two replicates will (almost) never agree 100% so how are discrepancies handled?

Currently, we recommend to visualise different replicates on their own, to confirm that they are of sufficient quality, and then combine them, retaining the proteins that have been quantified over all replicated experiments. This allows to obtain localisation information over all replicated data. We however do not explicitly assess the variability using this approach. This could be done by analysing replicated independently and then compare the coherence of the classification results. Proteins that are only observed in some replicates could be rescued by repeating the analysis using only the relevant (possibly unique) replicate(s).

**Comment by lmsimp** [comment]
@lgatto where is the above figure? I would like to add it to [the response to reviewers](https://github.com/lmsimp/bioc-pRoloc-hyperLOPIT-workflow/blob/master/replies-to-reviewers.pdf)

**Comment by lgatto** [comment]
It isn't anywhere in the repo. You can either right-click and download, or re-generate it with the exact code chunk above.
