### ISSUE TITLE
Add pd and tl results to pRolocdata?

### ISSUE THREAD

**Issue by lmsimp** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#42]
In the manuscript we load the results of the `phenoDisco` and TL algorithms under the hood:

PD
```r
f0 <- dir(extdatadir, full.names = TRUE,
          pattern = "bpw-pdres.rds")
```

TL
```r
tlfile <- dir(extdatadir, full.names = TRUE,
              pattern = "bpw-tlopt.rds")
```

SVM
```r
svmf <- dir(extdatadir, full.names = TRUE,
              pattern = "bpw-svmopt.rds") 
```

I do agree with Daniel it is annoying when you follow the manuscript you can't produce the relevant plots yourself because the objects are not directly accessible by following the code.

What can we do @lgatto? Do you think we should add a column to the hyperLOPIT `MSnSet` in `pRolocdata` for each of these results? Or directly show how to load these results using the `dir` command? The latter is messy. 

Although, loading the optimisations is tricky, they can't be stored in the `MSnSet` at least no the TL results.....

**Comment by lgatto** [comment]
The `pdres` results could be added indeed, but that won't help for the other data. I think it is perfectly fine to say that these results are precomputed and show how they can be loaded in addition to showing how they were computed.
