### ISSUE TITLE
Overview figure

### ISSUE THREAD

**Issue by lgatto** [lmsimp/bioc-pRoloc-hyperLOPIT-workflow#8]
We could prepare a overview figure of the workflow and refer to the specific sections.

**Comment by lmsimp** [comment]
Great idea!

**Comment by lgatto** [comment]
Also, a timetable as you had in your lab talk, summarising the functionality in `MSnbase`, `pRoloc` and `pRolocGUI`.

**Comment by lmsimp** [comment]
![img_6706](https://cloud.githubusercontent.com/assets/1698853/18749983/1965b974-80d1-11e6-972e-91680c3f1fb8.JPG)

**Comment by lmsimp** [comment]
Maybe a simplified version of something like this?
![overview](https://cloud.githubusercontent.com/assets/1698853/18759616/2bb2300c-80f5-11e6-88e3-0e2f94c179bb.png)

**Comment by lgatto** [comment]
Nice!
- Could you add a file to `Data export`, like the one at the beginning. 
- Will look at the figure when reading the paper again, and see how well the figure guides the reader.

**Comment by lmsimp** [comment]
![overview](https://cloud.githubusercontent.com/assets/1698853/18782302/bbbbb136-817d-11e6-835f-241ed2cddc68.png)

**Comment by lmsimp** [comment]
![overview](https://cloud.githubusercontent.com/assets/1698853/18782323/dadfa158-817d-11e6-8ee3-810a2ea0ff64.png)

**Comment by lmsimp** [comment]
We need to see if this fits in somewhere. It would be nice to include it.
